name: pricera-backend
region: sgp
services:
  - name: api
    github:
      repo: Dilhanahpc/phone_price_view
      branch: main
      deploy_on_push: true
    source_dir: /phone_price_backend
    run_command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: "https://dilhanahpc.github.io/phone_price_view"
      - key: PYTHON_VERSION
        scope: RUN_TIME
        value: "3.11"
